### ISSUE TITLE
Slow update

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#93]
This is my first night using the Comics RSS feed and waiting for it to update (using mainly FeedReader, but have the same RSS feed installed in Feedly and The Old Reader too), and though the new GoComics strips came through over an hour ago directly on their site, they're still not showing up through the Comics RSS feed on any of my readers.  

[ETA]  Over 4 hours now since GoComics new daily strips came through, but still nothing new on Refreshing my readers.

**Comment by ArtskydJ** [comment]
I'd made a mistake when making a change last night. I forgot to install some code on the server. This has been fixed now.

The comics should be up now.

**Comment by ghost** [comment]
The comics did come up right after above message, but still not updated so far tonight (about 2 hours after updated on GoComics site).

**Comment by ghost** [comment]
Will do with not opening new tickets on same issue.  My first time on GitHub, thought that once you "closed" a ticket, that was it.  

The Wandering Melon is still not updating for me on FeedReader, just Nov. 13, not Nov. 17 (obviously, have refreshed).  What reader do you use? (I need a free one.  I prefer the rendering/quality of the comics best on FeedReader so far, but realize that the reader may be part of my problem.)

[ETA]  The Wandering Melon finally updated on Feedly.com.  I unfortunately don't like the look of the comics as well as on FeedReader; Feedly changes the size from the originals quite often.  Maybe there's something I can do about that in the settings. 

<img width="955" alt="untitled1" src="https://user-images.githubusercontent.com/45058249/48662687-9a2a3a80-ea42-11e8-9af7-7fe4aa9d4a8a.png">

**Comment by ghost** [comment]
I use [rss2email](https://github.com/turbodog/rss2email) (Python script) to get RSS/Atom feeds in my email client (Mac Mail.app). I prefer it to using a dedicated RSS reader. Each RSS reader applies its own stylesheet so you get a different formatting (font size/color, image size/position, etc.).
rss2email let's my apply my own CSS stylesheet.

You can also use [CodeRed RSS Preview](https://www.coderedcorp.com/tools/rss-preview/) to check if a RSS feed is updating properly.

"The Wandering Melon" email resized
![screencap-1542479317463](https://user-images.githubusercontent.com/9649385/48664488-05056100-ea97-11e8-88da-907749d78da3.png)

"The Wandering Melon" email original size
![screencap-1542479552603](https://user-images.githubusercontent.com/9649385/48664501-37af5980-ea97-11e8-8e32-82554f659cba.png)

Feeds as email messages
![screencap-1542479679724](https://user-images.githubusercontent.com/9649385/48664513-9379e280-ea97-11e8-8282-47abe3d16b08.png)

"The Wandering Melon" RSS preview
![screencap-1542479964199](https://user-images.githubusercontent.com/9649385/48664557-45b1aa00-ea98-11e8-9d21-b53c402c035a.png)

**Comment by ghost** [comment]
@megadr01d:  Thanks for your help.  That's all above my skill level.  I just want to use a free dedicated online reader.

**Comment by ghost** [comment]
@ArtskydJ:  If you use a different reader/setup than megadr01d, even if a paid one, I'd be interested in hearing your recommendations.  

I've signed up for probably 6-7 different free online readers to try out, and FeedReader is still the best at maintaining the visual style, so even if it's one of the slowest updating (and it still is, comparatively speaking), that's a price I'm willing to pay for the style quality.  

Thanks very much for all your help and for creating and maintaining this RSS feed.

**Comment by ghost** [comment]
While you wait for @ArtskydJ's response and, in case you haven't tried these already, here are some (haven't really tried any but I keep them in my bookmarks).

https://www.commafeed.com
https://www.inoreader.com
~https://feedly.com~ Noticed you already tried it
https://www.newspipe.org

**Comment by ArtskydJ** [comment]
Sorry for my late reply.

I personally use feedly. I used to use feedreader. Before that I used Google Reader (RIP lol).

Feedly is probably messing with the image scale. Maybe I'll try switching at some point, but now I'm using feedly's Read Later feature. I also really like having a native android app. This makes it so I can't really use a bunch of decent-looking but web-app-only readers. :disappointed: 

---

Regarding the reported issue... Slow update.

1. The code to scrape the site takes about 30 minutes due to rate-limiting on gocomics.com. I've investigated trying to pull from different machines (different IP addresses), but it starts to get complicated, and probably expensive. So as of right now, it's going to be at least 30 minutes after gocomics updates.

2. I am not detecting when gocomics updates. I am running my script automatically at the same time each day. I'd be willing to change the time. So if my script is consistently launched 1.5 hours after gocomics updates, then I should be able to move the launch time an hour sooner.

I check my feed reader some time in the evening. Then I go to bed. Then gocomics updates. I guess it doesn't really affect me if the rss items are available 2 hours after they're available on gocomics.

However, I should be able to better than 2 hours, so I am re-opening this issue.

**Comment by ArtskydJ** [comment]
I originally closed this issue since I thought I had resolved the issue. However, it looks like you want the rss feeds to update sooner each night.

Do you know when gocomics updates? Is it pretty consistent?

**Comment by ghost** [comment]
Yes, pretty consistent.  It updates nightly by 1:40 a.m. EST.  

I still like the look of FeedReader best for maintaining image scale, so if you could possibly beta test there too, that would be awesome.

**Comment by ghost** [comment]
Update:  So Wednesday, Nov. 21, it worked like a charm.  I wish I'd checked it closer to actual GoComics update time, but it was definitely pretty fast, all updated when I checked about an hour after GC update, around 2:30 to 3 a.m. EST.

Thursday, I didn't have a chance to check it at all.  

This morning, strangely, they're still not updated (about 6 a.m. EST), so apparently something changed between Wednesday and today?

**Comment by ArtskydJ** [comment]
I don't think anything changed between Wed and today. The automated job crashed.

There's a bug where sometimes when it crashes, and later automated runs don't work. #83

I just re-ran it, and the today's comics are just now live.

**Comment by ArtskydJ** [comment]
Closing due to #102, and because the scraper has been quite consistent for a while.
